### ISSUE TITLE
Runs browserify many times instead of once, glob-run@0.1.6

### ISSUE THREAD

**Issue by dabowheel** [fahad19/glob-run#1]
This command did not work as I expected it. Instead of running browserify once with all the files found, it ran multiple times.

C:\Users\Miguel\workspace\grackle>glob-run browserify controllers/*.js -o temp.js
(node) sys is deprecated. Use util instead.
(node) util.print is deprecated. Use console.log instead.

> > browserify controllers/admin.js -o temp.js
> > browserify controllers/blog.js -o temp.js
> > browserify controllers/blogList.js -o temp.js
> > browserify controllers/component.js -o temp.js
> > browserify controllers/forgotPassword.js -o temp.js
> > browserify controllers/login.js -o temp.js
> > browserify controllers/main.js -o temp.js
> > browserify controllers/menu.js -o temp.js
> > browserify controllers/profile.js -o temp.js
> > browserify controllers/resetPassword.js -o temp.js
> > browserify controllers/resetPasswordResult.js -o temp.js
> > browserify controllers/signup.js -o temp.js
> > browserify controllers/splash.js -o temp.js
> > browserify controllers/verifyEmail.js -o temp.js

**Comment by mojoaxel** [comment]
this is the documented behavior of this library.
